name: update_db

on:
  push:
  schedule:
    - cron: 00 05 * * *

jobs:
  update_db:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v1
        id: install-r

      - name: Install pak and query dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), ".github/r-depends.rds")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.R_LIBS_USER }}/*
            !${{ env.R_LIBS_USER }}/pak
          key: dp-tweets-${{ steps.install-r.outputs.installed-r-version }}-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: dp-tweets-${{ steps.install-r.outputs.installed-r-version }}-

      - name: Install system dependencies 
        run: |
          pak::local_system_requirements(execute = TRUE)
          pak::local_install_dev_deps(upgrade = TRUE)
        shell: Rscript {0}
        
      - name: Update database
        run: Rscript nflfastr_database.R
        
        
      - name: Commit and Push
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Updated on `date`" || echo "No changes to commit"
          git push || echo "No changes to commit"
